variables:
    GIT_SUBMODULE_STRATEGY: recursive
    LLNL_SLURM_SCHEDULER_PARAMETERS: "--nodes=1 -p pbatch -A asccasc"

stages:
    - build
    - test


###########
# GCC CPU #
###########

build_cpu-linux_gcc6.1.0:
    stage: build
    before_script:
        - module reset
        - module load gcc/6.1.0
        - export CXX=$(which g++)
        - |- 
            if [ -z ${CXX} ]; then
                exit 1
            fi
    script:
        - mkdir build
        - cd build
        - cmake -DBUILD_TESTING=ON -DZFP_WITH_CUDA=OFF -DBUILD_UTILITIES=OFF ..
        - make -j
    artifacts:
        paths:
            - build
    tags:
        - batch
        - surface

test_cpu-linux_gcc6.1.0:
    stage: test
    script:
        - cd build
        - ctest -E "Cuda"
    after_script:
        - rm -rf build
    dependencies:
        - build_cpu-linux_gcc6.1.0
    tags:
        - batch
        - surface

##############
# NVIDIA GPU #
##############

build_gpu-linux_cuda10.1.168:
    stage: build
    before_script:
        - module reset
        - module load opt
        - module load cuda/10.1.168
    script:
        - mkdir build
        - cd build
        - cmake -DBUILD_TESTING=ON -DZFP_WITH_CUDA=ON -DZFP_WITH_OPENMP=OFF -DBUILD_UTILITIES=OFF ..
        - make -j
    artifacts:
        paths:
            - build
    tags:
        - batch
        - surface

test_gpu-linux_cuda10.1.168:
    stage: test
    script:
        - cd build
        - ctest -R "Cuda"
    after_script:
        - rm -rf build
    dependencies:
        - build_gpu-linux_cuda10.1.168
    tags:
        - batch
        - surface
