language:
  - generic

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc-8.4
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-8.4
            - g++-8.4
            - gfortran-8.4
            - libpython3.5-dev
            - python3-numpy
            - python3-pip
      env: CC='gcc-8.4' CXX='g++-8.4' FC='gfortran-8.4' FORTRAN_STANDARD='2003' PYTHON_VERSION='3.5' COVERAGE='ON'

    - os: linux
      dist: xenial
      compiler: clang-10.0
      before_install:
        - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
      addons: &clang100
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-10.0']
          packages:
            - clang-10.0
            - g++-7
            - gfortran-6
            - libpython3.5-dev
            - python3-numpy
            - python3-pip
      env: CC='clang-10.0' CXX='clang++-10.0' FC='gfortran-6' FORTRAN_STANDARD='2003' PYTHON_VERSION='3.5'

    - os: osx
      osx_image: xcode12
      compiler: gcc
      env: CC='gcc' CXX='g++' PYTHON_VERSION='3.5'

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv root; fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$PYTHON_VERSION" = "3.5" ]; then
        pyenv install 3.5.0;
        export PYTHON_INCLUDE_DIR=$(pyenv root)/versions/3.5.0/include/python3.5m;
        export PYTHON_LIBRARY=$(pyenv root)/versions/3.5.0/lib/libpython3.5m.a;
        export PYTHON_EXECUTABLE=$(pyenv root)/versions/3.5.0/bin/python3.5m;
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        $PYTHON_EXECUTABLE -m pip install --upgrade 'pip<21';
        $PYTHON_EXECUTABLE -m pip install -r ${TRAVIS_BUILD_DIR}/python/requirements.txt;
    fi

  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        export PYTHON_EXECUTABLE=/usr/bin/python$PYTHON_VERSION;
        source /etc/lsb-release;
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$PYTHON_VERSION" = "3.5" ]; then
        export PYTHON_INCLUDE_DIR=/usr/include/python3.5m;
        export PYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so;
        sudo $PYTHON_EXECUTABLE -m pip install --upgrade 'pip<21';
        sudo $PYTHON_EXECUTABLE -m pip install --upgrade cython;
    fi

  - printenv | grep PYTHON
  - ./travis.sh

after_success:
  - if [[ -n "${COVERAGE}" ]]; then bash <(curl -s https://codecov.io/bash); fi
