version: 0.5.5-{build}

environment:
  # zfpy only build for Release builds (otherwise need debug python libs python27_d.lib)
  matrix:
#    - COMPILER: mingw
#      GENERATOR: MinGW Makefiles
#      PLATFORM: Win32
#      BUILD_TYPE: Debug

    - COMPILER: mingw
      GENERATOR: MinGW Makefiles
      PLATFORM: Win32
      BUILD_TYPE: Release
      PYTHON_VERSION: 27

#    - COMPILER: mingw-w64
#      GENERATOR: MinGW Makefiles
#      PLATFORM: x64
#      BUILD_TYPE: Debug

    - COMPILER: mingw-w64
      GENERATOR: MinGW Makefiles
      PLATFORM: x64
      BUILD_TYPE: Release
      PYTHON_VERSION: 35

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: x64
      BUILD_TYPE: Debug

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: x64
      BUILD_TYPE: Release
      PYTHON_VERSION: 27

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: Win32
      BUILD_TYPE: Debug

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: Win32
      BUILD_TYPE: Release
      PYTHON_VERSION: 35

    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015 Win64
      PLATFORM: x64
      BUILD_TYPE: Debug

    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015 Win64
      PLATFORM: x64
      BUILD_TYPE: Release
      PYTHON_VERSION: 35

    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015
      PLATFORM: Win32
      BUILD_TYPE: Debug

    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015
      PLATFORM: Win32
      BUILD_TYPE: Release
      PYTHON_VERSION: 27

install:
  - if "%COMPILER%"=="mingw" set PATH=C:\MinGW\bin;%PATH%
  - if "%COMPILER%"=="mingw-w64" set PATH=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%

  # set env vars for Python system dir
  - ps: |
      if ($env:PYTHON_VERSION) {
        $env:PYTHON_DIR = "C:\Python$env:PYTHON_VERSION"
        if ($env:PLATFORM -eq "x64") {
          $env:PYTHON_DIR = "$env:PYTHON_DIR-x64"
        }

        $env:PYTHON_LIB_PATH = "$env:PYTHON_DIR\libs"
        if ($env:COMPILER -eq "msvc") {
          $env:PYTHON_LIB_PATH = "$env:PYTHON_LIB_PATH\python$env:PYTHON_VERSION.lib"
        } else {
          # mingw
          $env:PYTHON_LIB_PATH = "$env:PYTHON_LIB_PATH\libpython$env:PYTHON_VERSION.a"
        }
      }

  # placing these behind a conditional for some reason prevents CMake from picking up the virtualEnv
  - set PATH=%PYTHON_DIR%;%PYTHON_DIR%\Scripts;%PATH%
  - pip install virtualenv

  - set VIRTUALENV_NAME=pyVirtualEnv
  - virtualenv %VIRTUALENV_NAME%
  - "%VIRTUALENV_NAME%\\Scripts\\activate.bat"
  - pip install -r python\requirements.txt
  - python --version

build_script:
  - sh appveyor.sh
