version: 0.5.4-{build}

environment:
  matrix:
    - COMPILER: mingw
      GENERATOR: MinGW Makefiles
      PLATFORM: Win32
      BUILD_TYPE: Debug

    - COMPILER: mingw
      GENERATOR: MinGW Makefiles
      PLATFORM: Win32
      BUILD_TYPE: Release

    - COMPILER: mingw-w64
      GENERATOR: MinGW Makefiles
      PLATFORM: x64
      BUILD_TYPE: Debug

    - COMPILER: mingw-w64
      GENERATOR: MinGW Makefiles
      PLATFORM: x64
      BUILD_TYPE: Release

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: x64
      BUILD_TYPE: Debug

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: x64
      BUILD_TYPE: Release

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: Win32
      BUILD_TYPE: Debug

    - COMPILER: msvc
      GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: Win32
      BUILD_TYPE: Release

    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015 Win64
      PLATFORM: x64
      BUILD_TYPE: Debug

    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015 Win64
      PLATFORM: x64
      BUILD_TYPE: Release

    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015
      PLATFORM: Win32
      BUILD_TYPE: Debug

    - COMPILER: msvc
      GENERATOR: Visual Studio 14 2015
      PLATFORM: Win32
      BUILD_TYPE: Release

install:
  - if "%COMPILER%"=="mingw" set PATH=C:\MinGW\bin;%PATH%
  - if "%COMPILER%"=="mingw-w64" set PATH=C:\MinGW\bin;%PATH%

build_script:
  - mkdir build
  - cd build

  # build/test without OpenMP, with CFP (and custom namespace)
  - if "%COMPILER%"=="msvc" ctest -V -C "%BUILD_TYPE%" -DGENERATOR="%GENERATOR%" -DBUILD_CFP=ON -DCFP_NAMESPACE=cfp2 -DBUILD_OPENMP=OFF -DBUILD_CUDA=OFF -S %APPVEYOR_BUILD_FOLDER%/cmake/appveyor.cmake
  - if not "%COMPILER%"=="msvc" ctest -V -C "%BUILD_TYPE%" -DGENERATOR="%GENERATOR%" -DBUILD_CFP=ON -DCFP_NAMESPACE=cfp2 -DBUILD_OPENMP=OFF -DBUILD_CUDA=OFF -S %APPVEYOR_BUILD_FOLDER%/cmake/appveyor.cmake

  - rm -rf ./*

  # build/test with OpenMP
  - if "%COMPILER%"=="msvc" ctest -V -C "%BUILD_TYPE%" -DGENERATOR="%GENERATOR%" -DBUILD_OPENMP=ON -DOMP_TESTS_ONLY=ON -S %APPVEYOR_BUILD_FOLDER%/cmake/appveyor.cmake
  - if not "%COMPILER%"=="msvc" ctest -V -C "%BUILD_TYPE%" -DGENERATOR="%GENERATOR%" -DBUILD_OPENMP=ON -DOMP_TESTS_ONLY=ON -S %APPVEYOR_BUILD_FOLDER%/cmake/appveyor.cmake
