trigger:
- misc/azure-pipelines-gui

jobs:
- job: 'vs2017'

  strategy:
    matrix:
      64:
        GENERATOR: 'Visual Studio 15 2017 Win64'
        BUILD_TYPE: 'Debug'
      32:
        GENERATOR: 'Visual Studio 15 2017'
        BUILD_TYPE: 'Release'

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - bash: |
      mkdir build
      cd build
      cmake -G '$(GENERATOR)' -DCMAKE_BUILD_TYPE='$(BUILD_TYPE)' ..
      cmake --build . --config '$(BUILD_TYPE)'
    displayName: 'Build'

  - bash: |
      cd build
      ctest -V -C '$(BUILD_TYPE)'
    displayName: 'Test'

- job: 'vs2015'

  strategy:
    matrix:
      64:
        GENERATOR: 'Visual Studio 14 2015 Win64'
        BUILD_TYPE: 'Debug'
      32:
        GENERATOR: 'Visual Studio 14 2015'
        BUILD_TYPE: 'Release'

  pool:
    vmImage: 'vs2015-win2012r2'

  steps:
  - bash: |
      mkdir build
      cd build
      cmake -G '$(GENERATOR)' -DCMAKE_BUILD_TYPE='$(BUILD_TYPE)' ..
      cmake --build . --config '$(BUILD_TYPE)'
    displayName: 'Build'

  - bash: |
      cd build
      ctest -V -C '$(BUILD_TYPE)'
    displayName: 'Test'
