trigger:
- misc/azure-pipelines-gui

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    mkdir build
    cd build
    cmake ..
    cmake --build .
  displayName: 'Build'

- script: |
    cd build
    ctest
  displayName: 'Tests'
