trigger:
- misc/azure-pipelines-gui

jobs:
- job: visual_studio_15_win64

  displayName: 'Visual Studio 15 2017 Win64'

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - bash: |
      mkdir build
      cd build
      cmake -G 'Visual Studio 15 2017 Win64' -DCMAKE_BUILD_TYPE='Debug' -DBUILD_CFP=ON  ..
      cmake --build . --config 'Debug'
    displayName: 'Build'

  - bash: |
      cd build
      ctest -V -C 'Debug'
    displayName: 'Tests'
